# This is a basic workflow to help you get started with Actions

name: Deploy Frontend | Backend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 17.x
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
                   
      
      - name: npm install 
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
        working-directory: ./frontend
        
      - name: frontend build
        run: npm run build --if-present
        working-directory: ./frontend
        
      - name: copy react to spring static resources
      - run: |
          mkdir -p hoak-backend/src/main/resources/static
          cp -a frontend/build/. hoak-backend/src/main/resources/static/
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: ./backend
      
      - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        name: SFTP Deploy
        with: 
          username: ${{secrets.USERNAME}}
          server: ${{secrets.IP}}
          ssh_private_key: ${{secrets.SSH}}
          local_path: backend/target/backend-0.0.1-SNAPSHOT.har
          remote_path: /home/nazimutkuatli/
